---
title: "Grocery Delivery Definitions"
output: html_document
---

### Grocery Delivery
- Grocery delivery is a service that delivers of a *single* grocery order to a given location (described below). You place your grocery order via a smartphone app or website. The order will be fulfilled up by a grocery store of your choosing.

### Buy Your Own Groceries
- This refers to the traditional way you would buy your groceries.

### Delivery Price
- Each grocery delivery will cost a flat fee regardless of the number of grocery deliveries. This includes all associated costs including tip.

### Delivery Date
- Delivery will be completed today, tomorrow, in 4 days, or in 7 days. Groceries will be delivered to the given location (described below).

### Delivery Agent
- Delivery will be performed by either a human or an autonomous vehicle. This will not impact the delivery price, process, or timing in any way.

### Location
- Grocery deliveries will be taken to one of three locations:
 - Doorstep: groceries will be placed, unsupervised, on your doorstep
 - Curbside: groceries are delivered to your curbside, you will have to come and pick the groceries up from the delivery vehicle
 - Neighborhood locker. groceries will be delivered to a secure, refrigerated locker that is within walking distance from your house"